# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='py-libtrust',
    version='1.0.4',
    description='Yet another docker/libtrust implement by python.',
    python_requires='>=3.6',
    project_urls={
        "homepage": "https://github.com/shabbywu/libtrust",
        "repository": "https://github.com/shabbywu/libtrust",
    },
    author='shabbywu',
    author_email='shabbywu@qq.com',
    license='Apache-2.0',
    packages=['libtrust', 'libtrust.keys'],
    package_dir={"": "."},
    package_data={},
    install_requires=['cryptography>=3.0.0', 'typing-extensions>=3.6.5'],
    extras_require={"dev": ["pytest==6.*,>=6.2.5", "pytest-cov==3.*,>=3.0.0"]},
)
